"""bootstrap.py — Environment initialization for the mod manager.

Provides:
  - ``ProgressCallback`` protocol for progress reporting.
  - ``_detect_software_dir()`` — locate the software root directory.
  - ``discover_user_config()`` — three-tier user_config.json discovery and merge.
  - ``generate_database()`` — generate or load Steam database (auto / manual).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Protocol

from .database_ops import discover_with_fallback
from .iojson import load_json_file, write_json_file
from .paths import normalize_posix

__all__ = [
    "ProgressCallback",
    "discover_user_config",
    "generate_database",
]


# ── Progress callback protocol ────────────────────────────────────────────────


class ProgressCallback(Protocol):
    """Progress notification callback.

    Args:
        step: Stage identifier ("scan" | "aggregate" | "compute" | "backup" |
              "apply" | "restore").
        finished: Number of completed items.
        total: Total number of items (-1 means unknown).
        message: Optional description text.
    """

    def __call__(self, step: str, finished: int, total: int, message: str = "") -> None:
        ...


# ── Internal helpers ──────────────────────────────────────────────────────────


def _detect_software_dir() -> str:
    """Locate the software root directory.

    Starting from the package directory (containing this file), walk upward
    until a ``pyproject.toml`` file is found.  If found, that parent directory
    is returned (development mode).  Otherwise the package directory itself
    (``site-packages/modmanager/``) is returned (installed mode).

    Returns:
        Absolute path in POSIX style.
    """
    current = Path(__file__).resolve().parent
    for parent in [current] + list(current.parents):
        if (parent / "pyproject.toml").exists():
            return normalize_posix(str(parent))
    return normalize_posix(str(current))


# ── Public API ────────────────────────────────────────────────────────────────


def discover_user_config(home_dir: str | None = None) -> dict:
    """Search three tiers of ``user_config.json`` and merge by priority.

    Tier order (last wins on conflict):
      1. ``~/.config/kmm/user_config.json``          (lowest priority)
      2. ``<software-root>/user_config.json``          (medium priority)
      3. ``$PWD/user_config.json``                     (highest priority)

    Each tier is loaded if present and valid (a JSON object/dict).  Invalid
    JSON or non-dict content at a tier causes that tier to be silently skipped
    without affecting other tiers.

    Args:
        home_dir:
            User home directory.  When ``None``, resolved from environment
            variables ``$HOME`` / ``%USERPROFILE%``, falling back to
            ``pathlib.Path.home()``.

    Returns:
        Merged ``user_config`` dictionary.

    Raises:
        FileNotFoundError:
            If none of the three search locations contains a valid
            ``user_config.json``.
    """
    if home_dir is None:
        home_dir = (
            os.environ.get("HOME")
            or os.environ.get("USERPROFILE")
            or str(Path.home())
        )

    # Build the three candidate paths
    tier1 = str(Path(home_dir) / ".config" / "kmm" / "user_config.json")
    tier2 = str(Path(_detect_software_dir()) / "user_config.json")
    tier3 = str(Path(os.getcwd()) / "user_config.json")

    tiers = [tier1, tier2, tier3]
    merged: dict = {}
    found_any = False

    for path in tiers:
        try:
            data = load_json_file(path)
        except Exception:
            continue
        if isinstance(data, dict):
            merged.update(data)
            found_any = True
        # non-dict JSON at a tier is silently skipped

    if not found_any:
        raise FileNotFoundError(
            f"No user_config.json found in any of the three search locations: "
            f"{tier1}, {tier2}, {tier3}"
        )

    return merged


def generate_database(
    mode: str,
    *,
    paths: list[str] | None = None,
    working_pathstyle: str = "linux",
    greedy_parsing: bool = False,
    on_progress: ProgressCallback | None = None,
    cache_path: str | None = None,
) -> dict:
    """Generate or load the Steam database.

    When a ``cache_path`` is provided and the file exists with a valid
    structure (at least a ``"steamlib"`` key containing a list), it is loaded
    and returned immediately — no scanning is performed.

    Otherwise the database is generated by scanning Steam libraries (``"auto"``
    mode) or from explicitly provided paths (``"manual"`` mode).  On success
    the result is optionally written to ``cache_path``.

    Args:
        mode:
            ``"auto"`` — automatically discover Steam library paths.
            ``"manual"`` — use the explicit *paths* argument.
        paths:
            List of VDF file paths or ``steamapps`` directory paths (only used
            when ``mode="manual"``).
        working_pathstyle:
            ``"linux"`` or ``"windows"`` path style.
        greedy_parsing:
            When ``True``, scan all discovered mods regardless of game scoping.
        on_progress:
            Optional progress callback.
        cache_path:
            Optional path to a JSON cache file.  If it exists and is valid it
            is loaded instead of scanning.  After a successful scan the result
            is written to this path.

    Returns:
        Database dictionary compatible with ``engine.compute_mapping``.

    Raises:
        ValueError:
            If *mode* is not ``"auto"`` or ``"manual"``, or if
            ``mode="manual"`` but *paths* is empty or ``None``.
    """
    # ── Validate mode ─────────────────────────────────────────────────────
    if mode not in ("auto", "manual"):
        raise ValueError(f"mode must be 'auto' or 'manual', got {mode!r}")

    if mode == "manual" and not paths:
        raise ValueError("manual mode requires at least one path")

    # ── Generate database ─────────────────────────────────────────────────
    if mode == "auto" and not paths:
        # Pure auto mode: no manual paths, no manual_only
        # ── Cache hit (pure auto mode only) ──
        if cache_path is not None:
            cache_file = Path(cache_path)
            if cache_file.exists() and cache_file.stat().st_size > 0:
                try:
                    cached = load_json_file(cache_path)
                    if isinstance(cached, dict) and isinstance(cached.get("steamlib"), list):
                        return cached
                except Exception:
                    # Invalid cache — fall through to regenerate
                    pass
        if on_progress is not None:
            on_progress("scan", 0, -1, "Discovering Steam libraries...")
        database = discover_with_fallback(
            working_pathstyle=working_pathstyle,
            greedy_parsing=greedy_parsing,
        )
        if on_progress is not None:
            on_progress("scan", 1, 1, "Steam discovery complete")
    elif mode == "manual":
        # Manual only: skip auto-discovery entirely
        from .path_resolver import resolve_directory_path
        resolved_paths = [resolve_directory_path(p, 'steamapps') for p in paths]
        manual_override_steamlibs = [
            {
                "path": p,
                "contains_libraryfolders_vdf": False,
                "game": [],
            }
            for p in resolved_paths
        ]
        if on_progress is not None:
            on_progress("scan", 0, -1, "Scanning provided library paths...")
        database = discover_with_fallback(
            working_pathstyle=working_pathstyle,
            manual_override_steamlibs=manual_override_steamlibs,
            greedy_parsing=greedy_parsing,
            manual_only=True,
        )
        if on_progress is not None:
            on_progress("scan", 1, 1, "Manual scan complete")
    else:
        # mode == "auto" with paths: combine auto + manual (manual_only=False)
        from .path_resolver import resolve_directory_path
        resolved_paths = [resolve_directory_path(p, 'steamapps') for p in paths]
        manual_override_steamlibs = [
            {
                "path": p,
                "contains_libraryfolders_vdf": False,
                "game": [],
            }
            for p in resolved_paths
        ]
        if on_progress is not None:
            on_progress("scan", 0, -1, "Discovering Steam libraries (auto + manual)...")
        database = discover_with_fallback(
            working_pathstyle=working_pathstyle,
            manual_override_steamlibs=manual_override_steamlibs,
            greedy_parsing=greedy_parsing,
            manual_only=False,
        )
        if on_progress is not None:
            on_progress("scan", 1, 1, "Combined scan complete")

    # ── Write cache ───────────────────────────────────────────────────────
    if cache_path is not None:
        write_json_file(cache_path, database)

    return database
